#ifndef _HAL_UART_CONFIG_H_
#define _HAL_UART_CONFIG_H_

#define HAL_UART_NUMBER_OF_UARTS		1
#define HAL_UART_TRANSMIT_BUFFER_SIZE		1000
#define HAL_UART_RECEIVE_BUFFER_SIZE		50
#define RECEIVED_ENABLED			true

#endif /* _HAL_UART_CONFIG_H_ */
