#ifndef _HAL_IOMAPPING_H_
#define _HAL_IOMAPPING_H_

#define LCD_DB4							PORT4_0
#define LCD_DB5							PORT4_1
#define LCD_DB6							PORT4_2
#define LCD_DB7							PORT4_3

#define LCD_RS							PORT4_4
#define LCD_RW							PORT4_5
#define LCD_E							PORT4_6
#define LCD_POWER						PORT4_7

#define ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL		0
#define ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL	4
#define ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL	2
//#define ioMapping_AUX_POWER_PWM_CHANNEL					0

#define ioMapping_OUTPUT_OVERVOLTAGE_COMPARATOR_OUTPUT	PORT1_7
#define ioMapping_OUTPUT_OVERCURRENT_COMPARATOR_OUTPUT	PORT2_0

#define ioMapping_POWER_ONn				PORT7_0
#define ioMapping_BOOTSTRAP_SHUTDOWNn	PORT7_3
#define ioMapping_1_WIRE_COMMUNICATION	PORT7_5
#define ioMapping_POWER_SOFT_STARTn		PORT7_4

#define ioMappint_IoutOffsetNullDAC		(0)


#if		ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 0
	#define PWM_B50_MODE						PCA0CPM0
	#define PWM_B50_HIGH_BYTE					PCA0CPH0
#elif	ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 1
	#define PWM_B50_MODE						PCA0CPM1
	#define PWM_B50_HIGH_BYTE					PCA0CPH1
#elif	ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 2
	#define PWM_B50_MODE						PCA0CPM2
	#define PWM_B50_HIGH_BYTE					PCA0CPH2
#elif	ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 3
	#define PWM_B50_MODE						PCA0CPM3
	#define PWM_B50_HIGH_BYTE					PCA0CPH3
#elif	ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 4
	#define PWM_B50_MODE						PCA0CPM4
	#define PWM_B50_HIGH_BYTE					PCA0CPH4
#elif	ioMapping_PWM_TO_TICK_SYNCHRONIZER_CHANNEL == 5
	#define PWM_B50_MODE						PCA0CPM5
	#define PWM_B50_HIGH_BYTE					PCA0CPH5
#endif

#if		ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 0
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM0
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH0
#elif	ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 1
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM1
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH1
#elif	ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 2
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM2
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH2
#elif	ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 3
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM3
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH3
#elif	ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 4
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM4
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH4
#elif	ioMapping_MAIN_BOOST_A_REGULATOR_PWM_CHANNEL == 5
	#define PWM_MAIN_BOOST_A_MODE				PCA0CPM5
	#define PWM_MAIN_BOOST_A_HIGH_BYTE			PCA0CPH5
#endif

#if		ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 0
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM0
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH0
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 1
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM1
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH1
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 2
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM2
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH2
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 3
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM3
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH3
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 4
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM4
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH4
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 5
	#define PWM_MAIN_BOOST_B_MODE				PCA0CPM5
	#define PWM_MAIN_BOOST_B_HIGH_BYTE			PCA0CPH5
#endif

#if		ioMapping_AUX_POWER_PWM_CHANNEL == 0
	#define PWM_AUX_POWER_MODE					PCA0CPM0
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH0
#elif	ioMapping_AUX_POWER_PWM_CHANNEL == 1
	#define PWM_AUX_POWER_MODE					PCA0CPM1
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH1
#elif	ioMapping_MAIN_BOOST_B_REGULATOR_PWM_CHANNEL == 2
	#define PWM_AUX_POWER_MODE					PCA0CPM2
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH2
#elif	ioMapping_AUX_POWER_PWM_CHANNEL == 3
	#define PWM_AUX_POWER_MODE					PCA0CPM3
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH3
#elif	ioMapping_AUX_POWER_PWM_CHANNEL == 4
	#define PWM_AUX_POWER_MODE					PCA0CPM4
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH4
#elif	ioMapping_AUX_POWER_PWM_CHANNEL == 5
	#define PWM_AUX_POWER_MODE					PCA0CPM5
	#define PWM_AUX_POWER_HIGH_BYTE				PCA0CPH5
#endif





#endif /* _HAL_IOMAPPING_H_ */
